const express=require('express'), http=require('http'), WebSocket=require('ws'), fs=require('fs'), path=require('path'), crypto=require('crypto'), bcrypt=require('bcryptjs'), multer=require('multer');
const PORT=3000, DATA=path.join(__dirname,'data.json'), UP=path.join(__dirname,'../uploads'); fs.mkdirSync(UP,{recursive:true});
let db={users:{},sessions:{},chats:{},messages:{},blocks:{},reputation:{},deletedChats:{},hiddenChats:{}}; if(fs.existsSync(DATA)) db={...db,...JSON.parse(fs.readFileSync(DATA,'utf8'))};
const save=()=>fs.writeFileSync(DATA,JSON.stringify(db,null,2)); const id=(n=12)=>crypto.randomBytes(n).toString('hex'); const now=()=>Date.now();
const app=express(); app.use(express.json({limit:'180mb'})); app.use('/uploads',express.static(UP));
const upload=multer({storage:multer.diskStorage({destination:UP, filename:(req,file,cb)=>cb(null,Date.now()+'-'+id(5)+'-'+file.originalname.replace(/[\\/]/g,'_'))}), limits:{fileSize:120*1024*1024}});
function token(){return id(24)} function auth(req,res,next){let t=(req.headers.authorization||'').replace('Bearer ',''); let u=db.sessions[t]; if(!u)return res.status(401).json({error:'auth'}); req.token=t; req.user=db.users[u.username]; req.device=u; next();}
function verifyStatus(username){let r=repFor(username); return r.score<-8?'suspicious':r.score>=5?'verified':'normal'}
function safe(u){return {username:u.username,displayName:u.displayName||u.username,bio:u.bio||'',avatar:u.avatar||'',banner:u.banner||'',profileColor:u.profileColor||'',avatarFrame:u.avatarFrame||'',createdAt:u.createdAt||0,lastSeen:u.lastSeen||0,status:sockets[u.username]?'online':'offline',fingerprint:u.fingerprint||'',privacy:u.privacy||{},verification:verifyStatus(u.username)}}
function chatSafe(c,me){let other=null;if(c.type==='private'){let o=c.members.find(x=>x!==me); other=safe(db.users[o]);} let msgs=db.messages[c.id]||[]; let last=msgs.filter(m=>!m.deletedForAll && !(m.deletedFor||[]).includes(me)).at(-1)||null; return {...c, other,last, unread:msgs.filter(m=>m.from!==me && !(m.readBy||[]).includes(me)).length};}
function repFor(username){let items=db.reputation[username]||[];let score=items.reduce((a,x)=>a+(x.type==='praise'?1:-2),0);return {score,items:items.slice(-80).reverse()}}
function emitToUser(username,payload){try{sockets[username]?.forEach(ws=>ws.send(JSON.stringify(payload)))}catch{}}
function emitChat(c,payload){c.members.forEach(m=>emitToUser(m,payload));}
function ensureSaved(username){let cid='saved__'+username; if(!db.chats[cid]){db.chats[cid]={id:cid,type:'saved',title:'Избранное',avatar:'',members:[username],admins:[username],createdAt:now(),pinned:[],muted:{}};db.messages[cid]=[];} return db.chats[cid];}
app.post('/api/register',(req,res)=>{let {username,password,displayName}=req.body; username=(username||'').toLowerCase().replace(/[^a-z0-9_]/g,''); if(!username||!password)return res.status(400).json({error:'bad'}); if(db.users[username])return res.status(409).json({error:'exists'}); db.users[username]={username,passwordHash:bcrypt.hashSync(password,10),displayName:username,bio:'',avatar:'',createdAt:now(),lastSeen:now(),fingerprint:id(8),settings:{theme:'crimson',notify:true,pin:'',autoLock:0,twofa:'',chatBg:'particles',fontSize:15,fontFamily:'system'},privacy:{lastSeen:'all',avatar:'all'},devices:[]}; ensureSaved(username); let t=token(); db.sessions[t]={username,createdAt:now(),device:req.headers['user-agent']||'PC'}; save(); res.json({token:t,user:safe(db.users[username])});});
app.post('/api/login',(req,res)=>{let {username,password,twofa}=req.body; username=(username||'').toLowerCase(); let u=db.users[username]; if(!u||!bcrypt.compareSync(password||'',u.passwordHash))return res.status(401).json({error:'login'}); if(u.settings?.twofa && u.settings.twofa!==twofa)return res.status(401).json({error:'twofa'}); u.lastSeen=now(); ensureSaved(username); let t=token(); db.sessions[t]={username,createdAt:now(),device:req.headers['user-agent']||'PC'}; save(); res.json({token:t,user:safe(u),settings:u.settings});});
app.post('/api/logout',auth,(req,res)=>{delete db.sessions[req.token]; save(); res.json({ok:true});});
app.get('/api/me',auth,(req,res)=>res.json({user:safe(req.user),settings:req.user.settings||{}}));
app.put('/api/me',auth,(req,res)=>{let b=req.body; Object.assign(req.user,{displayName:b.displayName??req.user.displayName,bio:b.bio??req.user.bio,avatar:b.avatar??req.user.avatar,banner:b.banner??req.user.banner,profileColor:b.profileColor??req.user.profileColor,avatarFrame:b.avatarFrame??req.user.avatarFrame}); if(b.settings) req.user.settings={...req.user.settings,...b.settings}; if(b.privacy) req.user.privacy={...req.user.privacy,...b.privacy}; save(); res.json({user:safe(req.user),settings:req.user.settings});});
app.post('/api/change-password',auth,(req,res)=>{let {oldPassword,newPassword}=req.body; if(!bcrypt.compareSync(oldPassword||'',req.user.passwordHash))return res.status(403).json({error:'password'}); req.user.passwordHash=bcrypt.hashSync(newPassword||'',10); save(); res.json({ok:true});});
app.get('/api/devices',auth,(req,res)=>{res.json({devices:Object.entries(db.sessions).filter(([,s])=>s.username===req.user.username).map(([token,s])=>({id:token.slice(0,8),current:token===req.token,createdAt:s.createdAt,device:s.device}))});});
app.post('/api/devices/logout-all',auth,(req,res)=>{for(const [t,s] of Object.entries(db.sessions)) if(s.username===req.user.username && t!==req.token) delete db.sessions[t]; save(); res.json({ok:true});});
app.get('/api/search',auth,(req,res)=>{let q=(req.query.q||'').toLowerCase(); res.json({users:Object.values(db.users).filter(u=>u.username!==req.user.username && (u.username.includes(q)||(u.displayName||'').toLowerCase().includes(q))).slice(0,30).map(safe)});});
app.get('/api/user/:username',auth,(req,res)=>{let u=db.users[req.params.username.toLowerCase()]; if(!u)return res.status(404).json({error:'not found'}); res.json({user:safe(u)});});


app.get('/api/stats/:username',auth,(req,res)=>{let u=req.params.username.toLowerCase(); if(!db.users[u])return res.status(404).json({error:'user'}); let sent=0,photos=0,files=0,groups=0,firstFriend=false; for(const c of Object.values(db.chats)){ if(c.members.includes(u)&&c.type==='private'&&c.members.length>1) firstFriend=true; if(c.admins?.includes(u)&&(c.type==='group'||c.type==='channel')) groups++; for(const m of (db.messages[c.id]||[])){ if(m.from===u){sent++; if(m.attachment){files++; if(String(m.attachment.type||'').startsWith('image/'))photos++;}} }} let achievements=[]; if(firstFriend)achievements.push('🏆 Первый друг'); if(sent>=1000)achievements.push('🏆 1000 сообщений'); if(db.users[u].createdAt && now()-db.users[u].createdAt>365*24*3600*1000)achievements.push('🏆 Год в NightVault'); if(groups>0)achievements.push('🏆 Создал группу'); res.json({username:u,sent,photos,files,groups,createdAt:db.users[u].createdAt||0,days:Math.max(0,Math.floor((now()-(db.users[u].createdAt||now()))/86400000)),achievements});});
app.get('/api/update-check',auth,(req,res)=>res.json({current:'0.9.0',latest:'0.9.0',available:false,notes:'NightVault актуален'}));

app.get('/api/reputation/:username',auth,(req,res)=>{let u=req.params.username.toLowerCase(); if(!db.users[u])return res.status(404).json({error:'user'}); res.json(repFor(u));});
app.post('/api/reputation/:username',auth,(req,res)=>{let u=req.params.username.toLowerCase(); if(!db.users[u])return res.status(404).json({error:'user'}); if(u===req.user.username)return res.status(400).json({error:'self'}); let type=req.body.type==='praise'?'praise':'report'; let reasons=(req.body.reasons||[]).map(String).slice(0,5); if(!reasons.length)return res.status(400).json({error:'reason'}); db.reputation[u]=db.reputation[u]||[]; db.reputation[u].push({id:id(6),from:req.user.username,type,reasons,createdAt:now()}); save(); res.json(repFor(u));});
app.post('/api/block/:username',auth,(req,res)=>{let x=req.params.username.toLowerCase(); db.blocks[req.user.username]=db.blocks[req.user.username]||[]; if(!db.blocks[req.user.username].includes(x))db.blocks[req.user.username].push(x); save(); res.json({ok:true});});
app.post('/api/unblock/:username',auth,(req,res)=>{db.blocks[req.user.username]=(db.blocks[req.user.username]||[]).filter(x=>x!==req.params.username.toLowerCase()); save(); res.json({ok:true});});
app.post('/api/avatar-data',auth,(req,res)=>{let {name,data}=req.body||{}; if(!name||!data)return res.status(400).json({error:'file'}); let raw=Buffer.from(data,'base64'); if(raw.length>8*1024*1024)return res.status(413).json({error:'too_large'}); let fn=Date.now()+'-'+id(5)+'-'+String(name).replace(/[\\/]/g,'_'); fs.writeFileSync(path.join(UP,fn),raw); const base=req.protocol+'://'+req.get('host'); req.user.avatar=base+'/uploads/'+fn; save(); res.json({avatar:req.user.avatar});});
app.post('/api/file-data',auth,(req,res)=>{let {name,type,data}=req.body||{}; if(!name||!data)return res.status(400).json({error:'file'}); let raw=Buffer.from(data,'base64'); if(raw.length>120*1024*1024)return res.status(413).json({error:'too_large'}); let fn=Date.now()+'-'+id(5)+'-'+String(name).replace(/[\\/]/g,'_'); fs.writeFileSync(path.join(UP,fn),raw); const base=req.protocol+'://'+req.get('host'); res.json({url:base+'/uploads/'+fn,name:String(name),size:raw.length,type:type||'application/octet-stream'});});
function privateId(a,b){return [a,b].sort().join('__')}
app.post('/api/chats/private/:username',auth,(req,res)=>{let o=req.params.username.toLowerCase(); if(!db.users[o])return res.status(404).json({error:'user'}); let cid=privateId(req.user.username,o); if(!db.chats[cid]){db.chats[cid]={id:cid,type:'private',members:[req.user.username,o],admins:[],createdAt:now(),pinned:[],muted:{}};db.messages[cid]=[];save();} res.json({chat:chatSafe(db.chats[cid],req.user.username)});});
app.post('/api/chats/group',auth,(req,res)=>{let title=req.body.title||'Новая группа', members=[...new Set([req.user.username,...(req.body.members||[]).filter(x=>db.users[x])])]; let cid='group_'+id(); db.chats[cid]={id:cid,type:req.body.channel?'channel':'group',title,avatar:req.body.avatar||'',members,admins:[req.user.username],createdAt:now(),pinned:[],muted:{},description:req.body.description||'',permissions:req.body.permissions||{write:true,invite:true,avatar:false}}; db.messages[cid]=[]; save(); res.json({chat:chatSafe(db.chats[cid],req.user.username)});});
app.get('/api/chats',auth,(req,res)=>{ensureSaved(req.user.username); res.json({chats:Object.values(db.chats).filter(c=>c.members.includes(req.user.username)&&!(db.deletedChats[req.user.username]||[]).includes(c.id)).map(c=>chatSafe(c,req.user.username)).sort((a,b)=>(b.last?.createdAt||b.createdAt)-(a.last?.createdAt||a.createdAt))});});
app.put('/api/chats/:id',auth,(req,res)=>{let c=db.chats[req.params.id]; if(!c||!c.members.includes(req.user.username))return res.status(404).json({error:'chat'}); if(c.type!=='private' && !c.admins.includes(req.user.username))return res.status(403).json({error:'admin'}); Object.assign(c,{title:req.body.title??c.title,description:req.body.description??c.description,avatar:req.body.avatar??c.avatar}); if(req.body.permissions)c.permissions={...(c.permissions||{}),...req.body.permissions}; if(req.body.addMembers)c.members=[...new Set([...c.members,...req.body.addMembers.filter(x=>db.users[x])])]; if(req.body.admins)c.admins=req.body.admins.filter(x=>c.members.includes(x)); save(); emitChat(c,{type:'chat_update',chat:chatSafe(c,req.user.username)}); res.json({chat:chatSafe(c,req.user.username)});});
app.post('/api/chats/:id/delete',auth,(req,res)=>{let c=db.chats[req.params.id]; if(!c||!c.members.includes(req.user.username))return res.status(404).json({error:'chat'}); db.deletedChats[req.user.username]=db.deletedChats[req.user.username]||[]; if(!db.deletedChats[req.user.username].includes(c.id))db.deletedChats[req.user.username].push(c.id); save(); res.json({ok:true});});
app.post('/api/chats/:id/mute',auth,(req,res)=>{let c=db.chats[req.params.id]; if(!c||!c.members.includes(req.user.username))return res.status(404).json({error:'chat'}); c.muted=c.muted||{}; c.muted[req.user.username]=!!req.body.muted; save(); res.json({ok:true});});
app.get('/api/chats/:id/messages',auth,(req,res)=>{let c=db.chats[req.params.id]; if(!c||!c.members.includes(req.user.username))return res.status(404).json({error:'chat'}); let list=(db.messages[c.id]||[]).filter(m=>!m.deletedForAll && !(m.deletedFor||[]).includes(req.user.username) && (!m.selfDestructAt||m.selfDestructAt>now())); res.json({messages:list});});
app.post('/api/chats/:id/messages',auth,(req,res)=>{let c=db.chats[req.params.id]; if(!c||!c.members.includes(req.user.username))return res.status(404).json({error:'chat'}); if(c.type==='channel' && !c.admins.includes(req.user.username))return res.status(403).json({error:'channel_admin'}); if(c.type==='group' && c.permissions?.write===false && !c.admins.includes(req.user.username))return res.status(403).json({error:'no_write_permission'}); let blocked=(db.blocks[c.members.find(x=>x!==req.user.username)]||[]).includes(req.user.username); if(blocked)return res.status(403).json({error:'blocked'}); let ttl=Number(req.body.ttl||0); let m={id:id(),chatId:c.id,from:req.user.username,text:req.body.text||'',attachment:req.body.attachment||null,replyTo:req.body.replyTo||null,reactions:{},editedAt:null,createdAt:now(),deliveredTo:[req.user.username],readBy:[req.user.username],deletedFor:[],deletedForAll:false,selfDestructAt:ttl?now()+ttl*1000:null}; db.messages[c.id]=db.messages[c.id]||[]; db.messages[c.id].push(m); c.members.forEach(x=>{db.deletedChats[x]=(db.deletedChats[x]||[]).filter(id=>id!==c.id)}); save(); emitChat(c,{type:'message',message:m,chat:chatSafe(c,req.user.username)}); res.json({message:m});});
app.put('/api/messages/:id',auth,(req,res)=>{for(const c of Object.values(db.chats)){let m=(db.messages[c.id]||[]).find(x=>x.id===req.params.id); if(m&&m.from===req.user.username){m.text=req.body.text??m.text; m.editedAt=now(); save(); emitChat(c,{type:'message_update',message:m}); return res.json({message:m});}} res.status(404).json({error:'msg'});});
app.delete('/api/messages/:id',auth,(req,res)=>{for(const c of Object.values(db.chats)){let m=(db.messages[c.id]||[]).find(x=>x.id===req.params.id); if(m&&c.members.includes(req.user.username)){if(req.query.all==='1'&&m.from===req.user.username)m.deletedForAll=true; else {m.deletedFor=m.deletedFor||[]; if(!m.deletedFor.includes(req.user.username))m.deletedFor.push(req.user.username);} save(); emitChat(c,{type:'message_delete',id:m.id,all:m.deletedForAll}); return res.json({ok:true});}} res.status(404).json({error:'msg'});});
app.post('/api/messages/:id/react',auth,(req,res)=>{for(const c of Object.values(db.chats)){let m=(db.messages[c.id]||[]).find(x=>x.id===req.params.id); if(m&&c.members.includes(req.user.username)){let e=req.body.emoji||'👍'; m.reactions=m.reactions||{}; m.reactions[e]=m.reactions[e]||[]; if(m.reactions[e].includes(req.user.username))m.reactions[e]=m.reactions[e].filter(x=>x!==req.user.username); else m.reactions[e].push(req.user.username); save(); emitChat(c,{type:'message_update',message:m}); return res.json({message:m});}} res.status(404).json({error:'msg'});});
app.post('/api/messages/:id/pin',auth,(req,res)=>{for(const c of Object.values(db.chats)){let m=(db.messages[c.id]||[]).find(x=>x.id===req.params.id); if(m&&c.members.includes(req.user.username)){c.pinned=c.pinned||[]; if(!c.pinned.includes(m.id))c.pinned.push(m.id); save(); emitChat(c,{type:'chat_update',chat:chatSafe(c,req.user.username)}); return res.json({ok:true});}} res.status(404).json({error:'msg'});});
app.post('/api/chats/:id/read',auth,(req,res)=>{let c=db.chats[req.params.id]; if(!c||!c.members.includes(req.user.username))return res.status(404).json({error:'chat'}); (db.messages[c.id]||[]).forEach(m=>{m.readBy=m.readBy||[]; if(!m.readBy.includes(req.user.username))m.readBy.push(req.user.username)}); save(); emitChat(c,{type:'read',chatId:c.id,user:req.user.username}); res.json({ok:true});});
app.get('/api/search-global',auth,(req,res)=>{let q=(req.query.q||'').toLowerCase(); let out=[]; for(const c of Object.values(db.chats).filter(c=>c.members.includes(req.user.username))){for(const m of (db.messages[c.id]||[])){if((m.text||'').toLowerCase().includes(q)||(m.attachment?.name||'').toLowerCase().includes(q))out.push({chat:chatSafe(c,req.user.username),message:m});}} res.json({results:out.slice(0,100)});});
const server=http.createServer(app), wss=new WebSocket.Server({server}), sockets={};
wss.on('connection',(ws,req)=>{let url=new URL(req.url,'http://x'), t=url.searchParams.get('token'), sess=db.sessions[t]; if(!sess){ws.close();return} let u=sess.username; sockets[u]=sockets[u]||new Set(); sockets[u].add(ws); db.users[u].lastSeen=now(); save(); ws.on('message',buf=>{try{let p=JSON.parse(buf.toString()); if(p.type==='typing'){let c=db.chats[p.chatId]; if(c) c.members.filter(x=>x!==u).forEach(x=>emitToUser(x,{type:'typing',chatId:p.chatId,user:u,active:!!p.active}));}}catch{}}); ws.on('close',()=>{sockets[u]?.delete(ws); if(!sockets[u]?.size) delete sockets[u]; if(db.users[u]){db.users[u].lastSeen=now(); save();}});});
server.listen(PORT,()=>console.log('NightVault v0.9 server http://0.0.0.0:'+PORT));
